### ISSUE TITLE
Video calibration does not work

### ISSUE THREAD

**Issue by proedie** [randallspicher/skin.lyrebird.rmod#32]
In Nexus, the video calibration does not work. The corners, subtitle position, and pixel ratio settings are selectable as expected, but cannot be moved.

**Comment by randallspicher** [comment]
I stopped updating Nexus a while ago, as I no longer have any devices still using it.  Omega is the current release.  

Does it work in Omega?  (it does for me with a mouse).  Note a couple of the images are not displaying in omega (the bar which shows where subtitles are, and the arrow things on the upper-left and bottom right corners to show the screen edges), so I'll need to fix that (window was expecting the images to mixed case names, while the actual images are all lowercase now in the skin).  if you are playing a video when calibrating, you might not notice those missing though (since you'll have the edges of the actual video, and actual subtitles to move around)

However, for the "moving" of things, that is controlled by kodi core, and not the skin.  It works with a mouse.  I'm not clear how (or if) it is expected to work with a keyboard/remote.

**Comment by randallspicher** [comment]
update, there were some updates in nexus that required skin changes for the keyboard movement.
It's fixed in the Omega Beta.

**Comment by proedie** [comment]
Correct me if I'm wrong, but I think Nexus is still officially supported and comes with Debian stable. I prefer stable releases over bleeding edge for my Kodi, because I just want to watch stuff and not fiddle with the system.

Anyway, when I change the skin to something else, I can calibrate the video just fine with the 'keyboard' (actually, my remote). Since this is also a workaround, I won't shout and scream if you won't fix this bug. :wink:

(But it still seems to be a bug in the skin.)

**Comment by randallspicher** [comment]
Fixed in the 8.2.0 release
