### ISSUE TITLE
Higher CPU usage on HOME screen when idle

### ISSUE THREAD

**Issue by nagysifa** [randallspicher/skin.lyrebird.rmod#6]
Hello again!
First of all THANX for keeping this skin alive!

I use it daily on all my KODI 18.9 devices:
Wintel MiniPC - Windows x86 ( Intel Atom Z3737F / 2GB RAM )
Regular PC - Windows x64
RPI3 - Libreelec distribution
RPI2 - Libreelec distribution

On all of these systems I noticed that the CPU usage is a lot higher ( like double ) when idleing in homescreen.
That is not a problem for a powerfull hardware, but for my less powerfull hardware is a problem - they get HOT ! ( Wintel / RPI )
They are a LOT cooler when they are playing x264 1080p videos or music ... 
When I switch back to the default skin ( estuary ) the CPU usage is normal in any menu I select.
I have tried with screensaver, or without , all the settings I could change in KODI or the SKIN ... but it does not help. The CPU usage stays HIGH if KODI is left on homescreen playing nothing. If I open the Live TV channel list - the usage drops to normal.
I installed an "empty" KODI with just a PVR and the lyrebird.rmod skin, and the same happens ... here are some screenshots.
Could You please take a look into this ?

**lyrebird.rmod:**

![lyrebird rmod-01](https://user-images.githubusercontent.com/14113441/109429300-66993180-79fb-11eb-875e-02e55123a8de.jpg)
![lyrebird rmod-02](https://user-images.githubusercontent.com/14113441/109429301-6731c800-79fb-11eb-92d4-c664da81de77.jpg)
![lyrebird rmod-03](https://user-images.githubusercontent.com/14113441/109429302-67ca5e80-79fb-11eb-95cd-4353830a70ed.jpg)
![lyrebird rmod-04](https://user-images.githubusercontent.com/14113441/109429303-6862f500-79fb-11eb-8859-57cb77904cae.jpg)
![lyrebird rmod-05](https://user-images.githubusercontent.com/14113441/109429304-68fb8b80-79fb-11eb-8a4a-a50be5930c05.jpg)

**estuary:**

![estuary-01](https://user-images.githubusercontent.com/14113441/109429308-70bb3000-79fb-11eb-92a8-84f517a401a0.jpg)
![estuary-02](https://user-images.githubusercontent.com/14113441/109429309-71ec5d00-79fb-11eb-85aa-3a2702ae6f98.jpg)
![estuary-03](https://user-images.githubusercontent.com/14113441/109429310-7284f380-79fb-11eb-8813-5d8216b016e6.jpg)
![estuary-04](https://user-images.githubusercontent.com/14113441/109429311-731d8a00-79fb-11eb-8f91-43bd8aedad0c.jpg)
![estuary-05](https://user-images.githubusercontent.com/14113441/109429312-73b62080-79fb-11eb-874c-a0a8ae4ebd59.jpg)

Here are some LOG files :

**estuary:**
https://paste.ubuntu.com/p/MHVdfq7QXt/

**lyrebird.rmod:**
https://paste.ubuntu.com/p/phqZq8xhdZ/

Thanx in advance for all Your efforts, and kind regards : Zoltan.

**Comment by randallspicher** [comment]
1st, congratulations on having CPU usage under 50%.  I tend to see higher levels on my kodi devices.  If your device is getting overheated when at 25%, then you may need to investigate improving it's cooling.  (punch more holes in the case, add a fan, etc).  

I've noticed that whenever there is anything wanting to constantly change the display (such as autoscrolling text, or changing/rotating images), the cpu is hit hard. (lyrebird has tons of places where there is autoscrolling text), eg, things like titles and descriptions..  And, I can repeat that behavior on estuary as well by navigating to something that needs to scroll text, such as an icon view for something with a longer name, and go and put the focus on it so that it autoscrolls,  And things like the spinner (which you see when doing things like a library refresh) is a big hit as well.   There's also all the helper script plugins it uses (that the vanilla skin estuary does not).  I'm not really sure which ones really hit the cpu.  I've been thinking about migrating away from some of them for Matrix (several don't work there at all, at least not yet)

When watching an actual movie, that is generally all done with hardware acceleration on the graphics card, so ends up being less load than rendering the UI, which is all done in software.

lyrebird (and probably mimic) does seem to turn on autoscrolling a lot.  I could go though the code and restrict that to focused items as much as possible, but I'm not sure how much improvement that would make. The more stuff we put into the display, the harder the cpu is going to end up being hit to render it.   I'd note that one of the reasons I ended up on mimic/lyrebird in the first place was that it was much gentler on ths cpu (and memory) of my tiny media player box on my TV..  (skins like some of the aeon nox variations were hitting the cpu/memory limits)

I'll look into mitigating performance hits where I can, but I'm not sure how much effort I will be putting into the Leia version going forward.

**Comment by randallspicher** [comment]
Please go into settings -> skin settings -> general  and try turning "Enable autoscrolling for plot and review" to "off" and see if that makes a difference (or tell me if that is already set to off)

**Comment by nagysifa** [comment]
Thanx for the quick reply!

Autoscroll is turned off, but it does not affect the isue.

The previous screenshots are from a regular PC, and thats why the CPU usage seems low.
I do have all my devices drilled, heatsinked and actively cooled. Thanx for clarifying where the problem might be. If I want a decent looking and functionaling skin I need to accept that there will be higher CPU usage in menu-s when KODI is idleing.
For now I set that KODI starts with opening the TV channel list, so there is no overheating after the daily auto reboot.

I noticed the problem when the my Wintel BOX started to shut down randomly. I thought it was a software isue, I could not resolve it, the BOX was not even hot when it shut down. After a whole day guessing, I finaly ralized that the powersupply had a inflated condensator. Measuring the voltage on IDLE I've got 5.1V, whitch seamed fine. When the CPU drew some more power, the voltage got below 4.3V ( because the fawlty condensator ) and the BOX shut down.
The BOX is working 24/7 so it became obvious to me that if the CPU is running HIGH while IDLEing in KODI tha power supply will always suffer. I ordered a stronger PSU ( the old vas 3A, the new should be 5A and adjustable ) - but the unnecessary power "drain" will remain. This is true for my RPI2 and RPI3 boards - the also run 24/7.

Here are some screenshots of my Wintel BOX in "action" :
( I know the screenshots are with all my "unsupported" addons, but the same applies for an empty KODI installation as seen in my previous post )

![WINTEL01](https://user-images.githubusercontent.com/14113441/109474375-bcf68680-7a74-11eb-8233-4fc5425442a2.jpg)
![WINTEL02](https://user-images.githubusercontent.com/14113441/109474385-bec04a00-7a74-11eb-9b95-2a9acefa3a05.jpg)
![WINTEL03](https://user-images.githubusercontent.com/14113441/109474387-bff17700-7a74-11eb-8eeb-8e8390fc0c70.jpg)

**Comment by randallspicher** [comment]
I think I've found the major culprits (at least on most screens).  Many places in the skin use the `<animation>` tag, (usually for things like handling the focus hilight, instead of just making `<itemlatout>` and `<forcusedlayout>` slightly different.  where possible, I've removed those animations and make itemlayout and focusedlayout just use different the different colors (on the border, or what have you) which has made large improvements.  I also found some animation logic in the home screen, which, as far as I can tell, had no effect visually, but massively reduced the cpu usage when commented out.

The other major culprit is anywhere using the auto-scroll (when it needs to scroll text).  Most of those I've made obey the disable-auto-scroll skin setting, which can help.  

Another guilty item is the spinner (which uses animation to spin), there's one on the busy dialog, and another in the notifications (for notifications such as when it's busy indexing).  I've left those alone (for now) because there's no way to have a spinner (or rotating progress indicator) without animating.  Although I suppose I could use a setting to disable the animation and let the image just be static. (I'll think about that).

The last culprit is when it displays animated gifs.  That one, however, is really up to the user on whether or not they choose put those into their library, and they aren't as cpu intensive as the animation tag.
